apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxscgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fxscgr
  template:
    metadata:
      labels:
        app: fxscgr
    spec:
      containers:
      - image: okteto.dev/fxscgr:latest
        name: fxscgr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1ccf819b-b620-41a7-933e-2f02be2024f3"
        - name: Vless_Path
          value: "/vls2gfsyb7"
        - name: Vmess_UUID
          value: "1ccf819b-b620-41a7-933e-2f02be2024f3"
        - name: Vmess_Path
          value: "/vmtefjtf6"
        - name: Share_Path
          value: "/v2link"
